### ISSUE TITLE
Add average power consumption?

### ISSUE THREAD

**Issue by AndroPlus-org** [RikkaApps/TakoStats#1]
Thank you for providing this great tool!

Is it possible to add the data of average power consumption (mW)?
I'm measuring power efficiency in games but it requires power consumption data to calculate (average FPS / average power consumption).
https://androplus.org/en/entry/android-smartphone-benchmark-results/#Power_efficiency

I tested on vivo X90 Pro+ (Android 13) and couldn't find it on TakoStats 1.9.0.r229.

**Comment by AndroPlus-org** [comment]
It works wonderfully, thank you!

**Comment by RikkaW** [comment]
[tako-stats-1.10.4.r257.72f617889e-release.zip](https://github.com/RikkaApps/TakoStats/files/10526075/tako-stats-1.10.4.r257.72f617889e-release.zip)

**Comment by AndroPlus-org** [comment]
Thanks, it's perfect!
