### ISSUE TITLE
Full version is not working?

### ISSUE THREAD

**Issue by WibuCTer** [RikkaApps/TakoStats#13]
I spent money to unlock the full version but it still says it's a trial version, and now it says server error.
![Screenshot_20231209-235615_TakoStats](https://github.com/RikkaApps/TakoStats/assets/126878979/96d700bf-d2a4-436b-aa7d-cc5d7d1aeab5)
![Screenshot_20231210-000735_TakoStats](https://github.com/RikkaApps/TakoStats/assets/126878979/7b057586-6ef7-4e61-ad9e-acdd3f8bcecb)

**Comment by DGZone** [comment]
I also have an error

**Comment by Bimyourbae** [comment]
I'm the same way, how do I solve it?

**Comment by WibuCTer** [comment]
> I'm the same way, how do I solve it?

Idk, maybe wait until rikka fixes the server

**Comment by gamernoob24** [comment]
There is a ssl problem in the server
it should be fixed in 2 days or less

**Comment by WibuCTer** [comment]
Now it's fixed
