### ISSUE TITLE
Can't start on Lenovo Legion Y900 (ZUI)

### ISSUE THREAD

**Issue by AndroPlus-org** [RikkaApps/TakoStats#8]
When I tapped start button on Lenovo Legion Y900 (ZUI based on Android 13), it switches to the stop button for a moment and then immediately returns to the start button.
I'm using 1.11.0.r265.6a89eed578.

The crash happens around 04-15 17:41:22
[log.txt](https://github.com/RikkaApps/TakoStats/files/11239034/log.txt)
The result of getprop is here:
[prop.txt](https://github.com/RikkaApps/TakoStats/files/11239036/prop.txt)

Could you fix this problem?

**Comment by RikkaW** [comment]
Please send `/system/framework/framework.jar` on your device.

**Comment by AndroPlus-org** [comment]
Here's the framework.jar:
https://drive.google.com/file/d/1zVG0MfiSIK8ZGsx-MPhJ2odQ9FVImvIg/view?usp=sharing

**Comment by RikkaW** [comment]
Does enabling "Compatibility mode overlay" work?

**Comment by AndroPlus-org** [comment]
No, I enabled it but same thing happens.

**Comment by RikkaW** [comment]
[tako-stats-1.12.1.r280.a3dd23fee3-release.zip](https://github.com/RikkaApps/TakoStats/files/11276099/tako-stats-1.12.1.r280.a3dd23fee3-release.zip)
Please try this build.

**Comment by AndroPlus-org** [comment]
Thank you, now it works!
